package pe.bcrp.lbtr.ws.auth;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2025-11-27T12:57:40.023-05:00
 * Generated source version: 3.5.5
 *
 */
@WebService(targetNamespace = "http://lbtr.bcrp.gob.pe", name = "LBTRAutenticacionService")
@XmlSeeAlso({ObjectFactory.class})
public interface LBTRAutenticacionService {

    @WebMethod(action = "tns:logon")
    @Action(input = "tns:logon", output = "http://lbtr.bcrp.gob.pe/LBTRAutenticacionService/logonResponse", fault = {@FaultAction(className = LBTRSessionException.class, value = "http://lbtr.bcrp.gob.pe/LBTRAutenticacionService/logon/Fault/LBTRSessionException")})
    @RequestWrapper(localName = "logon", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.auth.Logon")
    @ResponseWrapper(localName = "logonResponse", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.auth.LogonResponse")
    @WebResult(name = "sid", targetNamespace = "")
    public java.lang.String logon(

        @WebParam(name = "codigo", targetNamespace = "")
        java.lang.String codigo,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "ksim", targetNamespace = "")
        java.lang.String ksim,
        @WebParam(name = "firma", targetNamespace = "")
        java.lang.String firma
    ) throws LBTRSessionException;

    @WebMethod(action = "tns:logoff")
    @Action(input = "tns:logoff", output = "http://lbtr.bcrp.gob.pe/LBTRAutenticacionService/logoffResponse", fault = {@FaultAction(className = LBTRSessionException.class, value = "http://lbtr.bcrp.gob.pe/LBTRAutenticacionService/logoff/Fault/LBTRSessionException")})
    @RequestWrapper(localName = "logoff", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.auth.Logoff")
    @ResponseWrapper(localName = "logoffResponse", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.auth.LogoffResponse")
    @WebResult(name = "respuesta", targetNamespace = "")
    public boolean logoff(

        @WebParam(name = "codigo", targetNamespace = "")
        java.lang.String codigo,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "ksim", targetNamespace = "")
        java.lang.String ksim,
        @WebParam(name = "firma", targetNamespace = "")
        java.lang.String firma
    ) throws LBTRSessionException;
}
