package pe.bcrp.lbtr.ws.auth;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2025-11-27T12:57:40.037-05:00
 * Generated source version: 3.5.5
 *
 */
@WebServiceClient(name = "LBTRAutenticacionService",
                  wsdlLocation = "file:wsdl/LBTRAutenticacionService.wsdl",
                  targetNamespace = "http://lbtr.bcrp.gob.pe")
public class LBTRAutenticacionService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://lbtr.bcrp.gob.pe", "LBTRAutenticacionService");
    public final static QName LBTRAutenticacionServicePort = new QName("http://lbtr.bcrp.gob.pe", "LBTRAutenticacionServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/LBTRAutenticacionService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LBTRAutenticacionService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:wsdl/LBTRAutenticacionService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LBTRAutenticacionService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LBTRAutenticacionService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LBTRAutenticacionService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public LBTRAutenticacionService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LBTRAutenticacionService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LBTRAutenticacionService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns LBTRAutenticacionService
     */
    @WebEndpoint(name = "LBTRAutenticacionServicePort")
    public LBTRAutenticacionService getLBTRAutenticacionServicePort() {
        return super.getPort(LBTRAutenticacionServicePort, LBTRAutenticacionService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LBTRAutenticacionService
     */
    @WebEndpoint(name = "LBTRAutenticacionServicePort")
    public LBTRAutenticacionService getLBTRAutenticacionServicePort(WebServiceFeature... features) {
        return super.getPort(LBTRAutenticacionServicePort, LBTRAutenticacionService.class, features);
    }

}
