package pe.bcrp.lbtr.ws.transferencia;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2025-11-27T12:58:15.328-05:00
 * Generated source version: 3.5.5
 *
 */
@WebServiceClient(name = "LBTRTransferenciaService",
                  wsdlLocation = "file:wsdl/LBTRTransferenciaService.wsdl",
                  targetNamespace = "http://lbtr.bcrp.gob.pe")
public class LBTRTransferenciaService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://lbtr.bcrp.gob.pe", "LBTRTransferenciaService");
    public final static QName LBTRTransferenciaServicePort = new QName("http://lbtr.bcrp.gob.pe", "LBTRTransferenciaServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/LBTRTransferenciaService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LBTRTransferenciaService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:wsdl/LBTRTransferenciaService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LBTRTransferenciaService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LBTRTransferenciaService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LBTRTransferenciaService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public LBTRTransferenciaService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LBTRTransferenciaService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LBTRTransferenciaService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns LBTRTransferenciaService
     */
    @WebEndpoint(name = "LBTRTransferenciaServicePort")
    public LBTRTransferenciaService getLBTRTransferenciaServicePort() {
        return super.getPort(LBTRTransferenciaServicePort, LBTRTransferenciaService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LBTRTransferenciaService
     */
    @WebEndpoint(name = "LBTRTransferenciaServicePort")
    public LBTRTransferenciaService getLBTRTransferenciaServicePort(WebServiceFeature... features) {
        return super.getPort(LBTRTransferenciaServicePort, LBTRTransferenciaService.class, features);
    }

}
