package pe.bcrp.lbtr.ws.transferencia;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2025-11-27T12:58:15.316-05:00
 * Generated source version: 3.5.5
 *
 */
@WebService(targetNamespace = "http://lbtr.bcrp.gob.pe", name = "LBTRTransferenciaService")
@XmlSeeAlso({ObjectFactory.class})
public interface LBTRTransferenciaService {

    @WebMethod(action = "tns:instruirTransferencia")
    @Action(input = "tns:instruirTransferencia", output = "http://lbtr.bcrp.gob.pe/LBTRTransferenciaService/instruirTransferenciaResponse", fault = {@FaultAction(className = LBTRSessionException.class, value = "http://lbtr.bcrp.gob.pe/LBTRTransferenciaService/instruirTransferencia/Fault/LBTRSessionException"), @FaultAction(className = LBTRServiceException.class, value = "http://lbtr.bcrp.gob.pe/LBTRTransferenciaService/instruirTransferencia/Fault/LBTRServiceException")})
    @RequestWrapper(localName = "instruirTransferencia", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.transferencia.InstruirTransferencia")
    @ResponseWrapper(localName = "instruirTransferenciaResponse", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.transferencia.InstruirTransferenciaResponse")
    @WebResult(name = "respuestaLBTR", targetNamespace = "")
    public pe.bcrp.lbtr.ws.transferencia.RespuestaLBTR instruirTransferencia(

        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "datosTransferencia", targetNamespace = "")
        pe.bcrp.lbtr.ws.transferencia.DatosTransferencia datosTransferencia,
        @WebParam(name = "firma", targetNamespace = "")
        java.lang.String firma
    ) throws LBTRSessionException, LBTRServiceException;

    @WebMethod(action = "tns:confirmarAbonoCliente")
    @Action(input = "tns:confirmarAbonoCliente", output = "http://lbtr.bcrp.gob.pe/LBTRTransferenciaService/confirmarAbonoClienteResponse", fault = {@FaultAction(className = LBTRSessionException.class, value = "http://lbtr.bcrp.gob.pe/LBTRTransferenciaService/confirmarAbonoCliente/Fault/LBTRSessionException"), @FaultAction(className = LBTRServiceException.class, value = "http://lbtr.bcrp.gob.pe/LBTRTransferenciaService/confirmarAbonoCliente/Fault/LBTRServiceException")})
    @RequestWrapper(localName = "confirmarAbonoCliente", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.transferencia.ConfirmarAbonoCliente")
    @ResponseWrapper(localName = "confirmarAbonoClienteResponse", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.transferencia.ConfirmarAbonoClienteResponse")
    @WebResult(name = "respuestaLBTR", targetNamespace = "")
    public pe.bcrp.lbtr.ws.transferencia.RespuestaLBTR confirmarAbonoCliente(

        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "numRefLBTR", targetNamespace = "")
        java.lang.String numRefLBTR,
        @WebParam(name = "firma", targetNamespace = "")
        java.lang.String firma
    ) throws LBTRSessionException, LBTRServiceException;

    @WebMethod(action = "tns:instruirTransferenciaCavali")
    @Action(input = "tns:instruirTransferenciaCavali", output = "http://lbtr.bcrp.gob.pe/LBTRTransferenciaService/instruirTransferenciaCavaliResponse", fault = {@FaultAction(className = LBTRSessionException.class, value = "http://lbtr.bcrp.gob.pe/LBTRTransferenciaService/instruirTransferenciaCavali/Fault/LBTRSessionException"), @FaultAction(className = LBTRServiceException.class, value = "http://lbtr.bcrp.gob.pe/LBTRTransferenciaService/instruirTransferenciaCavali/Fault/LBTRServiceException")})
    @RequestWrapper(localName = "instruirTransferenciaCavali", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.transferencia.InstruirTransferenciaCavali")
    @ResponseWrapper(localName = "instruirTransferenciaCavaliResponse", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.transferencia.InstruirTransferenciaCavaliResponse")
    @WebResult(name = "respuestaLBTR", targetNamespace = "")
    public pe.bcrp.lbtr.ws.transferencia.RespuestaLBTR instruirTransferenciaCavali(

        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "datosTransferencia", targetNamespace = "")
        pe.bcrp.lbtr.ws.transferencia.DatosTransferencia datosTransferencia,
        @WebParam(name = "datosCavali", targetNamespace = "")
        pe.bcrp.lbtr.ws.transferencia.DatosCavali datosCavali,
        @WebParam(name = "firma", targetNamespace = "")
        java.lang.String firma
    ) throws LBTRSessionException, LBTRServiceException;
}
