
package pe.bcrp.lbtr.ws.transferencia;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.5
 * 2025-11-27T12:58:15.284-05:00
 * Generated source version: 3.5.5
 */

@WebFault(name = "LBTRSessionFault", targetNamespace = "http://lbtr.bcrp.gob.pe")
public class LBTRSessionException extends Exception {

    private pe.bcrp.lbtr.ws.transferencia.FaultInfo faultInfo;

    public LBTRSessionException() {
        super();
    }

    public LBTRSessionException(String message) {
        super(message);
    }

    public LBTRSessionException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public LBTRSessionException(String message, pe.bcrp.lbtr.ws.transferencia.FaultInfo lbtrSessionFault) {
        super(message);
        this.faultInfo = lbtrSessionFault;
    }

    public LBTRSessionException(String message, pe.bcrp.lbtr.ws.transferencia.FaultInfo lbtrSessionFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = lbtrSessionFault;
    }

    public pe.bcrp.lbtr.ws.transferencia.FaultInfo getFaultInfo() {
        return this.faultInfo;
    }
}
