
package pe.bcrp.lbtr.ws.consultas;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.5
 * 2025-11-27T12:57:57.759-05:00
 * Generated source version: 3.5.5
 */

@WebFault(name = "LBTRServiceFault", targetNamespace = "http://lbtr.bcrp.gob.pe")
public class LBTRServiceException extends Exception {

    private pe.bcrp.lbtr.ws.consultas.FaultInfo faultInfo;

    public LBTRServiceException() {
        super();
    }

    public LBTRServiceException(String message) {
        super(message);
    }

    public LBTRServiceException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public LBTRServiceException(String message, pe.bcrp.lbtr.ws.consultas.FaultInfo lbtrServiceFault) {
        super(message);
        this.faultInfo = lbtrServiceFault;
    }

    public LBTRServiceException(String message, pe.bcrp.lbtr.ws.consultas.FaultInfo lbtrServiceFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = lbtrServiceFault;
    }

    public pe.bcrp.lbtr.ws.consultas.FaultInfo getFaultInfo() {
        return this.faultInfo;
    }
}
