package pe.bcrp.lbtr.ws.consultas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2025-11-27T12:57:57.765-05:00
 * Generated source version: 3.5.5
 *
 */
@WebService(targetNamespace = "http://lbtr.bcrp.gob.pe", name = "LBTRConsultasService")
@XmlSeeAlso({ObjectFactory.class})
public interface LBTRConsultasService {

    @WebMethod(operationName = "lbtr_Monedas", action = "tns:lbtr_Monedas")
    @Action(input = "tns:lbtr_Monedas", output = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_MonedasResponse", fault = {@FaultAction(className = LBTRSessionException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_Monedas/Fault/LBTRSessionException"), @FaultAction(className = LBTRServiceException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_Monedas/Fault/LBTRServiceException")})
    @RequestWrapper(localName = "lbtr_Monedas", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrMonedas")
    @ResponseWrapper(localName = "lbtr_MonedasResponse", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrMonedasResponse")
    @WebResult(name = "moneda", targetNamespace = "")
    public java.util.List<pe.bcrp.lbtr.ws.consultas.BeanMoneda> lbtrMonedas(

        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid
    ) throws LBTRSessionException, LBTRServiceException;

    @WebMethod(operationName = "lbtr_AgentesBolsa", action = "tns:lbtr_AgentesBolsa")
    @Action(input = "tns:lbtr_AgentesBolsa", output = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_AgentesBolsaResponse", fault = {@FaultAction(className = LBTRSessionException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_AgentesBolsa/Fault/LBTRSessionException"), @FaultAction(className = LBTRServiceException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_AgentesBolsa/Fault/LBTRServiceException")})
    @RequestWrapper(localName = "lbtr_AgentesBolsa", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrAgentesBolsa")
    @ResponseWrapper(localName = "lbtr_AgentesBolsaResponse", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrAgentesBolsaResponse")
    @WebResult(name = "agenteBolsa", targetNamespace = "")
    public java.util.List<pe.bcrp.lbtr.ws.consultas.BeanAgenteBolsa> lbtrAgentesBolsa(

        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid
    ) throws LBTRSessionException, LBTRServiceException;

    @WebMethod(operationName = "lbtr_EntidadesFinancieras", action = "tns:lbtr_EntidadesFinancieras")
    @Action(input = "tns:lbtr_EntidadesFinancieras", output = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_EntidadesFinancierasResponse", fault = {@FaultAction(className = LBTRSessionException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_EntidadesFinancieras/Fault/LBTRSessionException"), @FaultAction(className = LBTRServiceException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_EntidadesFinancieras/Fault/LBTRServiceException")})
    @RequestWrapper(localName = "lbtr_EntidadesFinancieras", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrEntidadesFinancieras")
    @ResponseWrapper(localName = "lbtr_EntidadesFinancierasResponse", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrEntidadesFinancierasResponse")
    @WebResult(name = "entidadFinanciera", targetNamespace = "")
    public java.util.List<pe.bcrp.lbtr.ws.consultas.BeanEntidadFinanciera> lbtrEntidadesFinancieras(

        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid
    ) throws LBTRSessionException, LBTRServiceException;

    @WebMethod(operationName = "lbtr_CtasCtesEntidad", action = "tns:lbtr_CtasCtesEntidad")
    @Action(input = "tns:lbtr_CtasCtesEntidad", output = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_CtasCtesEntidadResponse", fault = {@FaultAction(className = LBTRSessionException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_CtasCtesEntidad/Fault/LBTRSessionException"), @FaultAction(className = LBTRServiceException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_CtasCtesEntidad/Fault/LBTRServiceException")})
    @RequestWrapper(localName = "lbtr_CtasCtesEntidad", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrCtasCtesEntidad")
    @ResponseWrapper(localName = "lbtr_CtasCtesEntidadResponse", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrCtasCtesEntidadResponse")
    @WebResult(name = "cuentaCorriente", targetNamespace = "")
    public java.util.List<pe.bcrp.lbtr.ws.consultas.BeanCuentaCorriente> lbtrCtasCtesEntidad(

        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "institucionID", targetNamespace = "")
        java.lang.String institucionID
    ) throws LBTRSessionException, LBTRServiceException;

    @WebMethod(operationName = "lbtr_NegCompraVentaME", action = "tns:lbtr_NegCompraVentaME")
    @Action(input = "tns:lbtr_NegCompraVentaME", output = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_NegCompraVentaMEResponse", fault = {@FaultAction(className = LBTRSessionException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_NegCompraVentaME/Fault/LBTRSessionException"), @FaultAction(className = LBTRServiceException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_NegCompraVentaME/Fault/LBTRServiceException")})
    @RequestWrapper(localName = "lbtr_NegCompraVentaME", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrNegCompraVentaME")
    @ResponseWrapper(localName = "lbtr_NegCompraVentaMEResponse", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrNegCompraVentaMEResponse")
    @WebResult(name = "negociacionCVME", targetNamespace = "")
    public java.util.List<pe.bcrp.lbtr.ws.consultas.BeanCompraVentaME> lbtrNegCompraVentaME(

        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "fechaLiquidacion", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar fechaLiquidacion
    ) throws LBTRSessionException, LBTRServiceException;

    @WebMethod(operationName = "lbtr_SaldosCtaCte", action = "tns:lbtr_SaldosCtaCte")
    @Action(input = "tns:lbtr_SaldosCtaCte", output = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_SaldosCtaCteResponse", fault = {@FaultAction(className = LBTRSessionException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_SaldosCtaCte/Fault/LBTRSessionException"), @FaultAction(className = LBTRServiceException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_SaldosCtaCte/Fault/LBTRServiceException")})
    @RequestWrapper(localName = "lbtr_SaldosCtaCte", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrSaldosCtaCte")
    @ResponseWrapper(localName = "lbtr_SaldosCtaCteResponse", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrSaldosCtaCteResponse")
    @WebResult(name = "saldo", targetNamespace = "")
    public java.util.List<pe.bcrp.lbtr.ws.consultas.BeanSaldoCtaCte> lbtrSaldosCtaCte(

        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "numCuenta", targetNamespace = "")
        java.lang.String numCuenta,
        @WebParam(name = "fecha", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar fecha
    ) throws LBTRSessionException, LBTRServiceException;

    @WebMethod(operationName = "lbtr_FacilidadesDisponibles", action = "tns:lbtr_FacilidadesDisponibles")
    @Action(input = "tns:lbtr_FacilidadesDisponibles", output = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_FacilidadesDisponiblesResponse", fault = {@FaultAction(className = LBTRSessionException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_FacilidadesDisponibles/Fault/LBTRSessionException"), @FaultAction(className = LBTRServiceException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_FacilidadesDisponibles/Fault/LBTRServiceException")})
    @RequestWrapper(localName = "lbtr_FacilidadesDisponibles", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrFacilidadesDisponibles")
    @ResponseWrapper(localName = "lbtr_FacilidadesDisponiblesResponse", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrFacilidadesDisponiblesResponse")
    @WebResult(name = "facilidadDisponible", targetNamespace = "")
    public java.util.List<pe.bcrp.lbtr.ws.consultas.BeanFacilidadInstitucion> lbtrFacilidadesDisponibles(

        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid
    ) throws LBTRSessionException, LBTRServiceException;

    @WebMethod(operationName = "lbtr_OperacionesRecibidas", action = "tns:lbtr_OperacionesRecibidas")
    @Action(input = "tns:lbtr_OperacionesRecibidas", output = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_OperacionesRecibidasResponse", fault = {@FaultAction(className = LBTRSessionException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_OperacionesRecibidas/Fault/LBTRSessionException"), @FaultAction(className = LBTRServiceException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_OperacionesRecibidas/Fault/LBTRServiceException")})
    @RequestWrapper(localName = "lbtr_OperacionesRecibidas", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrOperacionesRecibidas")
    @ResponseWrapper(localName = "lbtr_OperacionesRecibidasResponse", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrOperacionesRecibidasResponse")
    @WebResult(name = "operacion", targetNamespace = "")
    public java.util.List<pe.bcrp.lbtr.ws.consultas.BeanOperacion> lbtrOperacionesRecibidas(

        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "fechaLiquidacion", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar fechaLiquidacion
    ) throws LBTRSessionException, LBTRServiceException;

    @WebMethod(operationName = "lbtr_CobroTarifa", action = "tns:lbtr_CobroTarifa")
    @Action(input = "tns:lbtr_CobroTarifa", output = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_CobroTarifaResponse", fault = {@FaultAction(className = LBTRSessionException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_CobroTarifa/Fault/LBTRSessionException"), @FaultAction(className = LBTRServiceException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_CobroTarifa/Fault/LBTRServiceException")})
    @RequestWrapper(localName = "lbtr_CobroTarifa", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrCobroTarifa")
    @ResponseWrapper(localName = "lbtr_CobroTarifaResponse", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrCobroTarifaResponse")
    @WebResult(name = "beanCobroTarifa", targetNamespace = "")
    public pe.bcrp.lbtr.ws.consultas.BeanCobroTarifa lbtrCobroTarifa(

        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "periodo", targetNamespace = "")
        java.lang.String periodo
    ) throws LBTRSessionException, LBTRServiceException;

    @WebMethod(operationName = "lbtr_TipoCambio", action = "tns:lbtr_TipoCambio")
    @Action(input = "tns:lbtr_TipoCambio", output = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_TipoCambioResponse", fault = {@FaultAction(className = LBTRSessionException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_TipoCambio/Fault/LBTRSessionException"), @FaultAction(className = LBTRServiceException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_TipoCambio/Fault/LBTRServiceException")})
    @RequestWrapper(localName = "lbtr_TipoCambio", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrTipoCambio")
    @ResponseWrapper(localName = "lbtr_TipoCambioResponse", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrTipoCambioResponse")
    @WebResult(name = "tipoCambio", targetNamespace = "")
    public java.util.List<pe.bcrp.lbtr.ws.consultas.BeanTipoCambio> lbtrTipoCambio(

        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "codMoneda", targetNamespace = "")
        java.lang.String codMoneda,
        @WebParam(name = "fecha", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar fecha
    ) throws LBTRSessionException, LBTRServiceException;

    @WebMethod(operationName = "lbtr_MovimientosCtaCte", action = "tns:lbtr_MovimientosCtaCte")
    @Action(input = "tns:lbtr_MovimientosCtaCte", output = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_MovimientosCtaCteResponse", fault = {@FaultAction(className = LBTRSessionException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_MovimientosCtaCte/Fault/LBTRSessionException"), @FaultAction(className = LBTRServiceException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_MovimientosCtaCte/Fault/LBTRServiceException")})
    @RequestWrapper(localName = "lbtr_MovimientosCtaCte", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrMovimientosCtaCte")
    @ResponseWrapper(localName = "lbtr_MovimientosCtaCteResponse", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrMovimientosCtaCteResponse")
    @WebResult(name = "movimiento", targetNamespace = "")
    public java.util.List<pe.bcrp.lbtr.ws.consultas.BeanMovimientoCtaCte> lbtrMovimientosCtaCte(

        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "numCuenta", targetNamespace = "")
        java.lang.String numCuenta,
        @WebParam(name = "fecha", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar fecha
    ) throws LBTRSessionException, LBTRServiceException;

    @WebMethod(operationName = "lbtr_Conceptos", action = "tns:lbtr_Conceptos")
    @Action(input = "tns:lbtr_Conceptos", output = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_ConceptosResponse", fault = {@FaultAction(className = LBTRSessionException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_Conceptos/Fault/LBTRSessionException"), @FaultAction(className = LBTRServiceException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_Conceptos/Fault/LBTRServiceException")})
    @RequestWrapper(localName = "lbtr_Conceptos", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrConceptos")
    @ResponseWrapper(localName = "lbtr_ConceptosResponse", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrConceptosResponse")
    @WebResult(name = "conceptoLiquidacion", targetNamespace = "")
    public java.util.List<pe.bcrp.lbtr.ws.consultas.BeanConceptoLiquidacion> lbtrConceptos(

        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid
    ) throws LBTRSessionException, LBTRServiceException;

    @WebMethod(operationName = "lbtr_Tarifario", action = "tns:lbtr_Tarifario")
    @Action(input = "tns:lbtr_Tarifario", output = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_TarifarioResponse", fault = {@FaultAction(className = LBTRSessionException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_Tarifario/Fault/LBTRSessionException"), @FaultAction(className = LBTRServiceException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_Tarifario/Fault/LBTRServiceException")})
    @RequestWrapper(localName = "lbtr_Tarifario", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrTarifario")
    @ResponseWrapper(localName = "lbtr_TarifarioResponse", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrTarifarioResponse")
    @WebResult(name = "tarifario", targetNamespace = "")
    public java.util.List<pe.bcrp.lbtr.ws.consultas.BeanTarifa> lbtrTarifario(

        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid
    ) throws LBTRSessionException, LBTRServiceException;

    @WebMethod(operationName = "lbtr_OperacionesOtorgadas", action = "tns:lbtr_OperacionesOtorgadas")
    @Action(input = "tns:lbtr_OperacionesOtorgadas", output = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_OperacionesOtorgadasResponse", fault = {@FaultAction(className = LBTRSessionException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_OperacionesOtorgadas/Fault/LBTRSessionException"), @FaultAction(className = LBTRServiceException.class, value = "http://lbtr.bcrp.gob.pe/LBTRConsultasService/lbtr_OperacionesOtorgadas/Fault/LBTRServiceException")})
    @RequestWrapper(localName = "lbtr_OperacionesOtorgadas", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrOperacionesOtorgadas")
    @ResponseWrapper(localName = "lbtr_OperacionesOtorgadasResponse", targetNamespace = "http://lbtr.bcrp.gob.pe", className = "pe.bcrp.lbtr.ws.consultas.LbtrOperacionesOtorgadasResponse")
    @WebResult(name = "operacion", targetNamespace = "")
    public java.util.List<pe.bcrp.lbtr.ws.consultas.BeanOperacion> lbtrOperacionesOtorgadas(

        @WebParam(name = "sid", targetNamespace = "")
        java.lang.String sid,
        @WebParam(name = "fechaLiquidacion", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar fechaLiquidacion
    ) throws LBTRSessionException, LBTRServiceException;
}
