package pe.bcrp.lbtr.ws.consultas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2025-11-27T12:57:57.781-05:00
 * Generated source version: 3.5.5
 *
 */
@WebServiceClient(name = "LBTRConsultasService",
                  wsdlLocation = "file:wsdl/LBTRConsultasService.wsdl",
                  targetNamespace = "http://lbtr.bcrp.gob.pe")
public class LBTRConsultasService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://lbtr.bcrp.gob.pe", "LBTRConsultasService");
    public final static QName LBTRConsultasServicePort = new QName("http://lbtr.bcrp.gob.pe", "LBTRConsultasServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/LBTRConsultasService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LBTRConsultasService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:wsdl/LBTRConsultasService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LBTRConsultasService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LBTRConsultasService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LBTRConsultasService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public LBTRConsultasService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LBTRConsultasService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LBTRConsultasService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns LBTRConsultasService
     */
    @WebEndpoint(name = "LBTRConsultasServicePort")
    public LBTRConsultasService getLBTRConsultasServicePort() {
        return super.getPort(LBTRConsultasServicePort, LBTRConsultasService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LBTRConsultasService
     */
    @WebEndpoint(name = "LBTRConsultasServicePort")
    public LBTRConsultasService getLBTRConsultasServicePort(WebServiceFeature... features) {
        return super.getPort(LBTRConsultasServicePort, LBTRConsultasService.class, features);
    }

}
